// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

/** URL usada pelo Prisma CLI (migrate, etc.). Preferir conexão direta ao Postgres. */
const datasourceUrl =
  process.env["DIRECT_URL"] ??
  process.env["DIRECT_DATABASE_URL"] ??
  process.env["DATABASE_URL"];

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: datasourceUrl,
  },
});
