/**
 * Script de migração de imagens para Supabase Storage
 *
 * Percorre frontend/src/assets/, converte JPG/PNG para WebP,
 * faz upload para o bucket "site-assets" e gera o mapa de URLs.
 *
 * Uso: node scripts/migrate-assets.js
 */

require("dotenv").config()
const fs = require("fs")
const path = require("path")
const sharp = require("sharp")
const supabase = require("../lib/supabaseClient")

const BUCKET = "site-assets"
const ASSETS_DIR = path.resolve(__dirname, "../../frontend/src/assets")
const OUTPUT_FILE = path.resolve(__dirname, "../../frontend/src/config/asset-urls.js")
const WEBP_QUALITY = 80
const MAX_WIDTH = 1920 // Redimensionar imagens maiores que isso

// Extensões que serão convertidas para WebP
const RASTER_EXTS = [".jpg", ".jpeg", ".png", ".webp"]
// SVGs grandes com base64 embutido serão mantidos como estão por enquanto
const SVG_EXT = ".svg"

const randomSuffix = () => Math.random().toString(36).slice(2, 10)

async function ensureBucket() {
  const { data: buckets } = await supabase.storage.listBuckets()
  const exists = (buckets || []).some((b) => b.name === BUCKET)
  if (!exists) {
    const { error } = await supabase.storage.createBucket(BUCKET, { public: true })
    if (error) throw new Error(`Falha ao criar bucket: ${error.message}`)
    console.log(`✅ Bucket "${BUCKET}" criado`)
  } else {
    console.log(`✅ Bucket "${BUCKET}" já existe`)
  }
}

function getAllFiles(dir, fileList = []) {
  const entries = fs.readdirSync(dir, { withFileTypes: true })
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      getAllFiles(fullPath, fileList)
    } else {
      fileList.push(fullPath)
    }
  }
  return fileList
}

function getRelativePath(filePath) {
  return path.relative(ASSETS_DIR, filePath).replace(/\\/g, "/")
}

async function convertAndUpload(filePath) {
  const ext = path.extname(filePath).toLowerCase()
  const relativePath = getRelativePath(filePath)

  // Pular arquivos pequenos (< 50KB) — manter local
  const stats = fs.statSync(filePath)
  if (stats.size < 50 * 1024 && ext === SVG_EXT) {
    return null // SVGs pequenos ficam locais
  }

  let buffer
  let uploadPath
  let contentType

  if (RASTER_EXTS.includes(ext)) {
    // Converter para WebP
    try {
      const image = sharp(filePath)
      const metadata = await image.metadata()

      let pipeline = image
      if (metadata.width && metadata.width > MAX_WIDTH) {
        pipeline = pipeline.resize(MAX_WIDTH, null, { withoutEnlargement: true })
      }

      buffer = await pipeline.webp({ quality: WEBP_QUALITY }).toBuffer()
      uploadPath = relativePath.replace(/\.[^.]+$/, ".webp")
      contentType = "image/webp"
    } catch (err) {
      console.warn(`⚠️  Falha ao converter ${relativePath}: ${err.message}`)
      // Fallback: upload sem conversão
      buffer = fs.readFileSync(filePath)
      uploadPath = relativePath
      contentType = ext === ".png" ? "image/png" : "image/jpeg"
    }
  } else if (ext === SVG_EXT && stats.size > 500 * 1024) {
    // SVGs grandes: upload direto (podem conter base64)
    buffer = fs.readFileSync(filePath)
    uploadPath = relativePath
    contentType = "image/svg+xml"
  } else {
    return null // Pular outros arquivos
  }

  // Gerar path único para evitar conflitos
  const folder = path.dirname(uploadPath)
  const baseName = path.basename(uploadPath, path.extname(uploadPath))
  const finalExt = path.extname(uploadPath)
  const objectPath = `${folder}/${baseName}-${randomSuffix()}${finalExt}`

  const { error } = await supabase.storage.from(BUCKET).upload(objectPath, buffer, {
    contentType,
    upsert: false,
  })

  if (error) {
    // Se já existe, tentar com outro sufixo
    if (error.message?.includes("already exists") || error.statusCode === "409") {
      const retryPath = `${folder}/${baseName}-${randomSuffix()}${finalExt}`
      const { error: retryError } = await supabase.storage.from(BUCKET).upload(retryPath, buffer, {
        contentType,
        upsert: true,
      })
      if (retryError) {
        console.error(`❌ Falha no upload de ${relativePath}: ${retryError.message}`)
        return null
      }
      const { data } = supabase.storage.from(BUCKET).getPublicUrl(retryPath)
      return { original: relativePath, url: data.publicUrl }
    }
    console.error(`❌ Falha no upload de ${relativePath}: ${error.message}`)
    return null
  }

  const { data } = supabase.storage.from(BUCKET).getPublicUrl(objectPath)
  return { original: relativePath, url: data.publicUrl }
}

function generateAssetUrlsFile(mappings) {
  const entries = mappings
    .map(({ original, url }) => `  "${original}": "${url}"`)
    .join(",\n")

  const content = `// Auto-generated by migrate-assets.js — NÃO EDITAR MANUALMENTE
// Mapa de imagens migradas para Supabase Storage (WebP)
// Gerado em: ${new Date().toISOString()}

const ASSET_URLS = {
${entries}
}

export default ASSET_URLS

export function getAssetUrl(originalPath) {
  // Normalizar path (remover ./ e barras invertidas)
  const normalized = originalPath.replace(/^\\.\\/?/, "").replace(/\\\\/g, "/")
  return ASSET_URLS[normalized] || originalPath
}
`

  // Garantir que o diretório existe
  const dir = path.dirname(OUTPUT_FILE)
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }

  fs.writeFileSync(OUTPUT_FILE, content, "utf-8")
  console.log(`\n📄 Arquivo gerado: ${OUTPUT_FILE}`)
}

async function main() {
  console.log("🚀 Iniciando migração de assets para Supabase Storage...\n")
  console.log(`📁 Diretório de assets: ${ASSETS_DIR}`)
  console.log(`🪣 Bucket: ${BUCKET}`)
  console.log(`📐 Max width: ${MAX_WIDTH}px`)
  console.log(`🎨 WebP quality: ${WEBP_QUALITY}\n`)

  // 1. Garantir bucket
  await ensureBucket()

  // 2. Listar todos os arquivos
  const allFiles = getAllFiles(ASSETS_DIR)
  const eligibleFiles = allFiles.filter((f) => {
    const ext = path.extname(f).toLowerCase()
    const stats = fs.statSync(f)
    // Raster > 50KB ou SVG > 500KB
    if (RASTER_EXTS.includes(ext) && stats.size > 50 * 1024) return true
    if (ext === SVG_EXT && stats.size > 500 * 1024) return true
    return false
  })

  console.log(`\n📊 Total de arquivos: ${allFiles.length}`)
  console.log(`📊 Elegíveis para migração: ${eligibleFiles.length}\n`)

  // 3. Processar em lotes de 5 (evitar sobrecarregar)
  const BATCH_SIZE = 5
  const mappings = []
  let processed = 0
  let failed = 0

  for (let i = 0; i < eligibleFiles.length; i += BATCH_SIZE) {
    const batch = eligibleFiles.slice(i, i + BATCH_SIZE)
    const results = await Promise.all(batch.map(convertAndUpload))

    for (const result of results) {
      if (result) {
        mappings.push(result)
        processed++
      } else {
        failed++
      }
    }

    // Progresso
    const total = Math.min(i + BATCH_SIZE, eligibleFiles.length)
    process.stdout.write(`\r⏳ Processando: ${total}/${eligibleFiles.length} (${mappings.length} ok, ${failed} falhas)`)
  }

  console.log(`\n\n✅ Migração concluída!`)
  console.log(`   - Enviados: ${mappings.length}`)
  console.log(`   - Falhas: ${failed}`)

  // 4. Gerar arquivo de mapeamento
  if (mappings.length > 0) {
    generateAssetUrlsFile(mappings)
  }

  console.log("\n🎉 Pronto! Agora atualize os componentes para usar getAssetUrl().")
}

main().catch((err) => {
  console.error("\n💥 Erro fatal:", err.message)
  process.exit(1)
})
